### ISSUE TITLE
pdf download 

### ISSUE THREAD

**Issue by MusaRikhotso** [Team-Brogrammers/MidYearRegistration#10]
When a user clicks on a student's concession form, to view it in more detail, the download option for downloading that student's form doesn't work(ViewConcession)
So can we just have a download instead

**Comment by FullKickProductions** [comment]
Do you mean when they click on it in MainActivity? Or when they click on the PdfView in ViewConcessionActivity?

**Comment by MusaRikhotso** [comment]
ViewConcessions

**Comment by MusaRikhotso** [comment]
Download works
