### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by takatso-wits** [Team-Brogrammers/MidYearRegistration#11]
So my laptop decided to restart itself now I am trying to build my project and I get Malformed \uxxxx encoding.
can you guys help?

**Comment by FullKickProductions** [comment]
Maybe try cloning the project to a new folder, delete cache, sync Gradle, etc and see if that helps?

**Comment by takatso-wits** [comment]
Thank you Theo, I will try that and let you know how it went.
