### ISSUE TITLE
Sign up back button

### ISSUE THREAD

**Issue by MusaRikhotso** [Team-Brogrammers/MidYearRegistration#2]
The back button on the sign up UI is not working

**Comment by FullKickProductions** [comment]
This is caused by calling finish() in the Login activity when launching the sign-up activity. I have addressed the problem and will close this issue once I've pushed the commit.

**Comment by FullKickProductions** [comment]
Failing to call finish() makes Travis build fail. I'm going to look into overriding the onRestart method in LoginActivity.

**Comment by FullKickProductions** [comment]
Ok, solved it by overriding onBackPressed() in SignUpActivity. This time I'll wait for travis to approve the build before closing the issue.
