### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by takatso-wits** [Team-Brogrammers/MidYearRegistration#6]
I am struggling to uniquely identify the user in the database. How can I get around it?

**Comment by sipheT** [comment]
First you declare firebaseUser and firebaseAuth unstances globally using:
FirebaseUser firebaseUser;
FirebaseAuth firebaseAuth;

Then inside onCreate method you initialise them this way:
firebaseAuth = FirebaseAuth.getInstance();
firebaseUser = firebaseAuth.getCurrentUser();

Finally you can declare a string wherever you're sending your data:
String uid = firebaseUser.getUid;
uid is your unique user id

**Comment by takatso-wits** [comment]
Thank you... I will look into it before the end of the day today.
